version: 2

sources:
  - name: raw_data_circle
    description: raw dara circle sportswear from lw
    tables:
      - name: raw_cc_stock
        description: stock of products
      - name: raw_cc_sales
        description: sales of products
        tests:
          - unique:
              column_name: "(product_id || '-' || date_date)"
models:
  - name: stg_raw_data_circle__raw_cc_stock
    description: cleaning raw stock
    tests:
      - unique:
          column_name: product_id
  - name: stg_raw_data_circle__raw_cc_sales
    description: cleaning raw sales